name: dev_workflow

on:
  push:
    branches:
      - main

jobs:
    job_1:
        runs-on: ubuntu-latest
        steps:
            - name: create a new Folder
              run: mkdir new_folder
              
            - name: list folders
              run: ls -l

    job_2:
        runs-on: ubuntu-latest
        steps:
            - name: list folders
              run: ls -l

            - name: check docker
              run: docker --version

    job_3:
        runs-on: ubuntu-latest
        needs: [job_1, job_2]
        steps:
            - name: list folders
              run: ls -l

            - name: check docker
              run: docker --version